name: Docker

on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: "0 16 * * 1"
  push:
    branches:
      - main
    paths:
      - 1.6.x/**
      - 2.0.x/**
  pull_request:
    paths:
      - 1.6.x/**
      - 2.0.x/**

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker_latest:
    name: docker build (2.0.x)
    uses: Docker-Collection/reusable-workflows/.github/workflows/docker-build.yml@main
    with:
      docker_name: "ghcr.io/docker-collection/hetrixtools"
      platforms: "linux/amd64,linux/arm64,linux/arm/v7"
      context: "2.0.x"
      dockerfile: "2.0.x/Dockerfile"
      docker_label_author: "Efina"
      docker_label_title: "Docker Hetrixtools"
      docker_label_description: "Container for Hetrix Linux agent"

  docker_old:
    name: docker build (1.6.x)
    uses: Docker-Collection/reusable-workflows/.github/workflows/docker-build.yml@main
    with:
      docker_name: "ghcr.io/docker-collection/hetrixtools-1.6"
      context: "1.6.x"
      dockerfile: "1.6.x/Dockerfile"
      docker_label_author: "Efina"
      docker_label_title: "Docker Hetrixtools"
      docker_label_description: "Container for Hetrix Linux agent"
