name: Docker

on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: "0 16 * * 1"
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - start.sh
  pull_request:
    paths:
      - Dockerfile

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    name: docker build
    uses: Docker-Collection/reusable-workflows/.github/workflows/docker-build.yml@main
    with:
      docker_name: "ghcr.io/docker-collection/hetrixtools"
      docker_label_author: "Efina"
      docker_label_title: "Docker Hetrixtools"
      docker_label_description: "Container for Hetrix Linux agent"
