name: Docker

on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: "0 16 * * 1"
  push:
    branches:
      - main
    paths:
      - master/**
      - 1.6.x/**
      - 2.2.x/**
  pull_request:
    paths:
      - master/**
      - 1.6.x/**
      - 2.2.x/**

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker_latest:
    name: docker build (latest)
    uses: Docker-Collection/reusable-workflows/.github/workflows/docker-build.yml@main
    with:
      docker_name: "ghcr.io/docker-collection/hetrixtools"
      platforms: "linux/amd64,linux/arm64"
      context: "master"
      dockerfile: "master/Dockerfile"
      docker_label_author: "Efina"
      docker_label_title: "Docker Hetrixtools"
      docker_label_description: "A Container for HetrixTools Linux agent, master branch"

  docker_2_2:
    name: docker build (2.2.x)
    uses: Docker-Collection/reusable-workflows/.github/workflows/docker-build.yml@main
    with:
      docker_name: "ghcr.io/docker-collection/hetrixtools-2.2"
      platforms: "linux/amd64,linux/arm64"
      context: "2.2.x"
      dockerfile: "2.2.x/Dockerfile"
      docker_label_author: "Efina"
      docker_label_title: "Docker Hetrixtools"
      docker_label_description: "A Container for HetrixTools Linux agent, 2.2.x branch"

  docker_1_6:
    name: docker build (1.6.x)
    uses: Docker-Collection/reusable-workflows/.github/workflows/docker-build.yml@main
    with:
      docker_name: "ghcr.io/docker-collection/hetrixtools-1.6"
      context: "1.6.x"
      dockerfile: "1.6.x/Dockerfile"
      docker_label_author: "Efina"
      docker_label_title: "Docker Hetrixtools"
      docker_label_description: "A Container for HetrixTools Linux agent, 1.6.x branch"
